<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8d923e47e2a5cc0b0301192e10b73797
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8d923e47e2a5cc0b0301192e10b73797::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8d923e47e2a5cc0b0301192e10b73797::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
